services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kerberos
    ports:
      - 5432:5432
    volumes:
      - /postgres-data:/var/lib/postgresql/data

  api:
    build: ./Kerberos/Kerberos.Server/
    restart: always
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Database=kerberos;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Production

  client:
    build:
      context: ./Kerberos/Kerberos.Client/
      args:
        - VUE_APP_API_BASE_URL=/api
    restart: always
    depends_on:
      - api

  proxy:
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - client
      - api

